name: Deploy to Amazon EC2

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Build and push
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/amc.integration-api:latest
        no-cache: true
        build-args: |
          "PORT=${{ secrets.PORT }}"
          "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}"
          "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}"
          "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}"
          "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}"
          "SECRET=${{ secrets.SECRET }}"
          "ADS_REFRESH_TOKEN=${{ secrets.ADS_REFRESH_TOKEN }}"
          "ADS_CLIENT_ID=${{ secrets.ADS_CLIENT_ID }}"
          "ADS_CLIENT_SECRET=${{ secrets.ADS_CLIENT_SECRET }}"
          "ADS_AUTH_API=${{ secrets.ADS_AUTH_API }}"
          "ADS_AMC_API=${{ secrets.ADS_AMC_API }}"
          "ADS_AMC_INSTANCE=${{ secrets.ADS_AMC_INSTANCE }}"

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/amc.integration-api:latest
      - name: Delete Old Container
        run: sudo docker rm -f amc.integration-api
      - name: Run docker container
        run: sudo docker run -d -p ${{secrets.PORT}}:${{secrets.PORT}} --name amc.integration-api ${{secrets.DOCKER_USERNAME }}/amc.integration-api